import type {
  Advance,
  Competency,
  Discipline,
  MicroBuild,
  Module,
  University,
} from "../types";

export const modules: Module[] = [
  {
    id: "mod-psyc2017",
    universityId: "uni-manchester",
    code: "PSYC2017",
    title: "Research Methods and Statistics",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-law2041",
    universityId: "uni-manchester",
    code: "LAW2041",
    title: "Contract Law",
    discipline: "law",
    year: 2,
  },
  {
    id: "mod-hist2260",
    universityId: "uni-manchester",
    code: "HIST2260",
    title: "Sources and Methods in Modern History",
    discipline: "history",
    year: 2,
  },
  {
    id: "mod-bman2011",
    universityId: "uni-manchester",
    code: "BMAN2011",
    title: "Marketing Analysis and Strategy",
    discipline: "business",
    year: 2,
  },
  {
    id: "mod-nurs2301",
    universityId: "uni-manchester",
    code: "NURS2301",
    title: "Evidence-Based Practice",
    discipline: "nursing",
    year: 2,
  },
  {
    id: "mod-comp2001",
    universityId: "uni-manchester",
    code: "COMP2001",
    title: "Software Engineering",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-psyc2520",
    universityId: "uni-leeds",
    code: "PSYC2520",
    title: "Cognitive Psychology",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-law2086",
    universityId: "uni-leeds",
    code: "LAW2086",
    title: "Criminal Law",
    discipline: "law",
    year: 2,
  },
  {
    id: "mod-hist2400",
    universityId: "uni-leeds",
    code: "HIST2400",
    title: "The Practice of History",
    discipline: "history",
    year: 2,
  },
  {
    id: "mod-lubs2005",
    universityId: "uni-leeds",
    code: "LUBS2005",
    title: "Consumer Behaviour",
    discipline: "business",
    year: 2,
  },
  {
    id: "mod-comp2611",
    universityId: "uni-leeds",
    code: "COMP2611",
    title: "Artificial Intelligence",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-nurs2270",
    universityId: "uni-leeds",
    code: "NURS2270",
    title: "Applied Evidence-Based Nursing",
    discipline: "nursing",
    year: 2,
  },

  // University of Birmingham
  {
    id: "mod-birmingham-psyc2121",
    universityId: "uni-birmingham",
    code: "PSYC2121",
    title: "Cognitive Psychology",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-birmingham-law2122",
    universityId: "uni-birmingham",
    code: "LAW2122",
    title: "Contract Law",
    discipline: "law",
    year: 2,
  },
  {
    id: "mod-birmingham-hist2123",
    universityId: "uni-birmingham",
    code: "HIST2123",
    title: "Historiography and Historical Theory",
    discipline: "history",
    year: 2,
  },
  {
    id: "mod-birmingham-busi2124",
    universityId: "uni-birmingham",
    code: "BUSI2124",
    title: "Marketing Analysis and Strategy",
    discipline: "business",
    year: 2,
  },
  {
    id: "mod-birmingham-nurs2125",
    universityId: "uni-birmingham",
    code: "NURS2125",
    title: "Pathophysiology and Pharmacology",
    discipline: "nursing",
    year: 2,
  },
  {
    id: "mod-birmingham-comp2126",
    universityId: "uni-birmingham",
    code: "COMP2126",
    title: "Data Structures and Algorithms",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-birmingham-econ2127",
    universityId: "uni-birmingham",
    code: "ECON2127",
    title: "Intermediate Microeconomics",
    discipline: "economics",
    year: 2,
  },
  {
    id: "mod-birmingham-math2128",
    universityId: "uni-birmingham",
    code: "MATH2128",
    title: "Real Analysis",
    discipline: "maths",
    year: 2,
  },
  {
    id: "mod-birmingham-med2129",
    universityId: "uni-birmingham",
    code: "MED2129",
    title: "Cardiovascular and Respiratory Systems",
    discipline: "medicine",
    year: 2,
  },

  // University of Bristol
  {
    id: "mod-bristol-psyc2131",
    universityId: "uni-bristol",
    code: "PSYC2131",
    title: "Biological Psychology",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-bristol-law2132",
    universityId: "uni-bristol",
    code: "LAW2132",
    title: "Tort Law",
    discipline: "law",
    year: 2,
  },
  {
    id: "mod-bristol-hist2133",
    universityId: "uni-bristol",
    code: "HIST2133",
    title: "Approaches to History",
    discipline: "history",
    year: 2,
  },
  {
    id: "mod-bristol-busi2134",
    universityId: "uni-bristol",
    code: "BUSI2134",
    title: "Organisational Behaviour",
    discipline: "business",
    year: 2,
  },
  {
    id: "mod-bristol-nurs2135",
    universityId: "uni-bristol",
    code: "NURS2135",
    title: "Clinical Decision Making",
    discipline: "nursing",
    year: 2,
  },
  {
    id: "mod-bristol-comp2136",
    universityId: "uni-bristol",
    code: "COMP2136",
    title: "Databases",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-bristol-econ2137",
    universityId: "uni-bristol",
    code: "ECON2137",
    title: "Intermediate Macroeconomics",
    discipline: "economics",
    year: 2,
  },
  {
    id: "mod-bristol-math2138",
    universityId: "uni-bristol",
    code: "MATH2138",
    title: "Linear Algebra II",
    discipline: "maths",
    year: 2,
  },
  {
    id: "mod-bristol-med2139",
    universityId: "uni-bristol",
    code: "MED2139",
    title: "Human Disease and Therapeutics",
    discipline: "medicine",
    year: 2,
  },

  // University of Cambridge (no standalone undergraduate Business or Nursing degree)
  {
    id: "mod-cambridge-psyc2141",
    universityId: "uni-cambridge",
    code: "PSYC2141",
    title: "Social Psychology",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-cambridge-law2142",
    universityId: "uni-cambridge",
    code: "LAW2142",
    title: "Tort Law",
    discipline: "law",
    year: 2,
  },
  {
    id: "mod-cambridge-hist2143",
    universityId: "uni-cambridge",
    code: "HIST2143",
    title: "Historical Argument and Practice",
    discipline: "history",
    year: 2,
  },
  {
    id: "mod-cambridge-comp2146",
    universityId: "uni-cambridge",
    code: "COMP2146",
    title: "Artificial Intelligence",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-cambridge-econ2147",
    universityId: "uni-cambridge",
    code: "ECON2147",
    title: "Econometrics I",
    discipline: "economics",
    year: 2,
  },
  {
    id: "mod-cambridge-math2148",
    universityId: "uni-cambridge",
    code: "MATH2148",
    title: "Analysis II",
    discipline: "maths",
    year: 2,
  },
  {
    id: "mod-cambridge-med2149",
    universityId: "uni-cambridge",
    code: "MED2149",
    title: "Cardiovascular and Respiratory Systems",
    discipline: "medicine",
    year: 2,
  },

  // Cardiff University
  {
    id: "mod-cardiff-psyc2151",
    universityId: "uni-cardiff",
    code: "PSYC2151",
    title: "Developmental Psychology",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-cardiff-law2152",
    universityId: "uni-cardiff",
    code: "LAW2152",
    title: "EU Law",
    discipline: "law",
    year: 2,
  },
  {
    id: "mod-cardiff-hist2153",
    universityId: "uni-cardiff",
    code: "HIST2153",
    title: "Sources and Methods in Modern History",
    discipline: "history",
    year: 2,
  },
  {
    id: "mod-cardiff-busi2154",
    universityId: "uni-cardiff",
    code: "BUSI2154",
    title: "Strategic Management",
    discipline: "business",
    year: 2,
  },
  {
    id: "mod-cardiff-nurs2155",
    universityId: "uni-cardiff",
    code: "NURS2155",
    title: "Long-Term Conditions and Complex Care",
    discipline: "nursing",
    year: 2,
  },
  {
    id: "mod-cardiff-comp2156",
    universityId: "uni-cardiff",
    code: "COMP2156",
    title: "Computer Systems and Architecture",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-cardiff-econ2157",
    universityId: "uni-cardiff",
    code: "ECON2157",
    title: "Money and Banking",
    discipline: "economics",
    year: 2,
  },
  {
    id: "mod-cardiff-math2158",
    universityId: "uni-cardiff",
    code: "MATH2158",
    title: "Differential Equations",
    discipline: "maths",
    year: 2,
  },
  {
    id: "mod-cardiff-med2159",
    universityId: "uni-cardiff",
    code: "MED2159",
    title: "Pathology and Pharmacology",
    discipline: "medicine",
    year: 2,
  },

  // Durham University (no undergraduate Nursing degree)
  {
    id: "mod-durham-psyc2161",
    universityId: "uni-durham",
    code: "PSYC2161",
    title: "Individual Differences",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-durham-law2162",
    universityId: "uni-durham",
    code: "LAW2162",
    title: "Land Law",
    discipline: "law",
    year: 2,
  },
  {
    id: "mod-durham-hist2163",
    universityId: "uni-durham",
    code: "HIST2163",
    title: "Historical Skills and Sources",
    discipline: "history",
    year: 2,
  },
  {
    id: "mod-durham-busi2164",
    universityId: "uni-durham",
    code: "BUSI2164",
    title: "Financial Management",
    discipline: "business",
    year: 2,
  },
  {
    id: "mod-durham-comp2166",
    universityId: "uni-durham",
    code: "COMP2166",
    title: "Programming Paradigms",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-durham-econ2167",
    universityId: "uni-durham",
    code: "ECON2167",
    title: "Development Economics",
    discipline: "economics",
    year: 2,
  },
  {
    id: "mod-durham-math2168",
    universityId: "uni-durham",
    code: "MATH2168",
    title: "Abstract Algebra",
    discipline: "maths",
    year: 2,
  },
  {
    id: "mod-durham-med2169",
    universityId: "uni-durham",
    code: "MED2169",
    title: "Musculoskeletal and Neurological Systems",
    discipline: "medicine",
    year: 2,
  },

  // University of Edinburgh
  {
    id: "mod-edinburgh-psyc2171",
    universityId: "uni-edinburgh",
    code: "PSYC2171",
    title: "Psychopathology",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-edinburgh-law2172",
    universityId: "uni-edinburgh",
    code: "LAW2172",
    title: "Public Law",
    discipline: "law",
    year: 2,
  },
  {
    id: "mod-edinburgh-hist2173",
    universityId: "uni-edinburgh",
    code: "HIST2173",
    title: "The Practice of History",
    discipline: "history",
    year: 2,
  },
  {
    id: "mod-edinburgh-busi2174",
    universityId: "uni-edinburgh",
    code: "BUSI2174",
    title: "International Business Strategy",
    discipline: "business",
    year: 2,
  },
  {
    id: "mod-edinburgh-nurs2175",
    universityId: "uni-edinburgh",
    code: "NURS2175",
    title: "Evidence-Based Practice",
    discipline: "nursing",
    year: 2,
  },
  {
    id: "mod-edinburgh-comp2176",
    universityId: "uni-edinburgh",
    code: "COMP2176",
    title: "Web and Mobile Development",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-edinburgh-econ2177",
    universityId: "uni-edinburgh",
    code: "ECON2177",
    title: "Economics of Public Policy",
    discipline: "economics",
    year: 2,
  },
  {
    id: "mod-edinburgh-math2178",
    universityId: "uni-edinburgh",
    code: "MATH2178",
    title: "Numerical Analysis",
    discipline: "maths",
    year: 2,
  },
  {
    id: "mod-edinburgh-med2179",
    universityId: "uni-edinburgh",
    code: "MED2179",
    title: "Clinical and Communication Skills II",
    discipline: "medicine",
    year: 2,
  },

  // University of Exeter
  {
    id: "mod-exeter-psyc2181",
    universityId: "uni-exeter",
    code: "PSYC2181",
    title: "Conceptual and Historical Issues in Psychology",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-exeter-law2182",
    universityId: "uni-exeter",
    code: "LAW2182",
    title: "Equity and Trusts",
    discipline: "law",
    year: 2,
  },
  {
    id: "mod-exeter-hist2183",
    universityId: "uni-exeter",
    code: "HIST2183",
    title: "Making History: Theory and Practice",
    discipline: "history",
    year: 2,
  },
  {
    id: "mod-exeter-busi2184",
    universityId: "uni-exeter",
    code: "BUSI2184",
    title: "Consumer Behaviour",
    discipline: "business",
    year: 2,
  },
  {
    id: "mod-exeter-nurs2185",
    universityId: "uni-exeter",
    code: "NURS2185",
    title: "Pathophysiology and Pharmacology",
    discipline: "nursing",
    year: 2,
  },
  {
    id: "mod-exeter-comp2186",
    universityId: "uni-exeter",
    code: "COMP2186",
    title: "Software Engineering",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-exeter-econ2187",
    universityId: "uni-exeter",
    code: "ECON2187",
    title: "Intermediate Microeconomics",
    discipline: "economics",
    year: 2,
  },
  {
    id: "mod-exeter-math2188",
    universityId: "uni-exeter",
    code: "MATH2188",
    title: "Probability and Statistics",
    discipline: "maths",
    year: 2,
  },
  {
    id: "mod-exeter-med2189",
    universityId: "uni-exeter",
    code: "MED2189",
    title: "Human Disease and Therapeutics",
    discipline: "medicine",
    year: 2,
  },

  // University of Glasgow
  {
    id: "mod-glasgow-psyc2191",
    universityId: "uni-glasgow",
    code: "PSYC2191",
    title: "Cognitive Psychology",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-glasgow-law2192",
    universityId: "uni-glasgow",
    code: "LAW2192",
    title: "Constitutional and Administrative Law",
    discipline: "law",
    year: 2,
  },
  {
    id: "mod-glasgow-hist2193",
    universityId: "uni-glasgow",
    code: "HIST2193",
    title: "Historiography and Historical Theory",
    discipline: "history",
    year: 2,
  },
  {
    id: "mod-glasgow-busi2194",
    universityId: "uni-glasgow",
    code: "BUSI2194",
    title: "Operations Management",
    discipline: "business",
    year: 2,
  },
  {
    id: "mod-glasgow-nurs2195",
    universityId: "uni-glasgow",
    code: "NURS2195",
    title: "Applied Evidence-Based Nursing",
    discipline: "nursing",
    year: 2,
  },
  {
    id: "mod-glasgow-comp2196",
    universityId: "uni-glasgow",
    code: "COMP2196",
    title: "Artificial Intelligence",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-glasgow-econ2197",
    universityId: "uni-glasgow",
    code: "ECON2197",
    title: "Intermediate Macroeconomics",
    discipline: "economics",
    year: 2,
  },
  {
    id: "mod-glasgow-math2198",
    universityId: "uni-glasgow",
    code: "MATH2198",
    title: "Real Analysis",
    discipline: "maths",
    year: 2,
  },
  {
    id: "mod-glasgow-med2199",
    universityId: "uni-glasgow",
    code: "MED2199",
    title: "Cardiovascular and Respiratory Systems",
    discipline: "medicine",
    year: 2,
  },

  // Imperial College London (no Law, History, or Nursing degree)
  {
    id: "mod-imperial-busi2204",
    universityId: "uni-imperial",
    code: "BUSI2204",
    title: "Strategic Management",
    discipline: "business",
    year: 2,
  },
  {
    id: "mod-imperial-comp2206",
    universityId: "uni-imperial",
    code: "COMP2206",
    title: "Software Engineering",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-imperial-econ2207",
    universityId: "uni-imperial",
    code: "ECON2207",
    title: "Intermediate Microeconomics",
    discipline: "economics",
    year: 2,
  },
  {
    id: "mod-imperial-math2208",
    universityId: "uni-imperial",
    code: "MATH2208",
    title: "Linear Algebra II",
    discipline: "maths",
    year: 2,
  },
  {
    id: "mod-imperial-med2209",
    universityId: "uni-imperial",
    code: "MED2209",
    title: "Cardiovascular and Respiratory Systems",
    discipline: "medicine",
    year: 2,
  },

  // King's College London
  {
    id: "mod-kcl-psyc2211",
    universityId: "uni-kcl",
    code: "PSYC2211",
    title: "Biological Psychology",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-kcl-law2212",
    universityId: "uni-kcl",
    code: "LAW2212",
    title: "Criminal Law",
    discipline: "law",
    year: 2,
  },
  {
    id: "mod-kcl-hist2213",
    universityId: "uni-kcl",
    code: "HIST2213",
    title: "Sources and Methods in Modern History",
    discipline: "history",
    year: 2,
  },
  {
    id: "mod-kcl-busi2214",
    universityId: "uni-kcl",
    code: "BUSI2214",
    title: "Marketing Analysis and Strategy",
    discipline: "business",
    year: 2,
  },
  {
    id: "mod-kcl-nurs2215",
    universityId: "uni-kcl",
    code: "NURS2215",
    title: "Evidence-Based Practice",
    discipline: "nursing",
    year: 2,
  },
  {
    id: "mod-kcl-comp2216",
    universityId: "uni-kcl",
    code: "COMP2216",
    title: "Data Structures and Algorithms",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-kcl-econ2217",
    universityId: "uni-kcl",
    code: "ECON2217",
    title: "Econometrics I",
    discipline: "economics",
    year: 2,
  },
  {
    id: "mod-kcl-math2218",
    universityId: "uni-kcl",
    code: "MATH2218",
    title: "Differential Equations",
    discipline: "maths",
    year: 2,
  },
  {
    id: "mod-kcl-med2219",
    universityId: "uni-kcl",
    code: "MED2219",
    title: "Human Disease and Therapeutics",
    discipline: "medicine",
    year: 2,
  },

  // University of Liverpool
  {
    id: "mod-liverpool-psyc2221",
    universityId: "uni-liverpool",
    code: "PSYC2221",
    title: "Social Psychology",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-liverpool-law2222",
    universityId: "uni-liverpool",
    code: "LAW2222",
    title: "Contract Law",
    discipline: "law",
    year: 2,
  },
  {
    id: "mod-liverpool-hist2223",
    universityId: "uni-liverpool",
    code: "HIST2223",
    title: "Approaches to History",
    discipline: "history",
    year: 2,
  },
  {
    id: "mod-liverpool-busi2224",
    universityId: "uni-liverpool",
    code: "BUSI2224",
    title: "Consumer Behaviour",
    discipline: "business",
    year: 2,
  },
  {
    id: "mod-liverpool-nurs2225",
    universityId: "uni-liverpool",
    code: "NURS2225",
    title: "Clinical Decision Making",
    discipline: "nursing",
    year: 2,
  },
  {
    id: "mod-liverpool-comp2226",
    universityId: "uni-liverpool",
    code: "COMP2226",
    title: "Databases",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-liverpool-econ2227",
    universityId: "uni-liverpool",
    code: "ECON2227",
    title: "Money and Banking",
    discipline: "economics",
    year: 2,
  },
  {
    id: "mod-liverpool-math2228",
    universityId: "uni-liverpool",
    code: "MATH2228",
    title: "Abstract Algebra",
    discipline: "maths",
    year: 2,
  },
  {
    id: "mod-liverpool-med2229",
    universityId: "uni-liverpool",
    code: "MED2229",
    title: "Pathology and Pharmacology",
    discipline: "medicine",
    year: 2,
  },

  // LSE (no Medicine, Nursing, or standalone Computer Science / Mathematics degree)
  {
    id: "mod-lse-psyc2231",
    universityId: "uni-lse",
    code: "PSYC2231",
    title: "Social Psychology",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-lse-law2232",
    universityId: "uni-lse",
    code: "LAW2232",
    title: "Public Law",
    discipline: "law",
    year: 2,
  },
  {
    id: "mod-lse-hist2233",
    universityId: "uni-lse",
    code: "HIST2233",
    title: "Historical Argument and Practice",
    discipline: "history",
    year: 2,
  },
  {
    id: "mod-lse-busi2234",
    universityId: "uni-lse",
    code: "BUSI2234",
    title: "Strategic Management",
    discipline: "business",
    year: 2,
  },
  {
    id: "mod-lse-econ2237",
    universityId: "uni-lse",
    code: "ECON2237",
    title: "Intermediate Microeconomics",
    discipline: "economics",
    year: 2,
  },

  // Newcastle University
  {
    id: "mod-newcastle-psyc2241",
    universityId: "uni-newcastle",
    code: "PSYC2241",
    title: "Developmental Psychology",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-newcastle-law2242",
    universityId: "uni-newcastle",
    code: "LAW2242",
    title: "Tort Law",
    discipline: "law",
    year: 2,
  },
  {
    id: "mod-newcastle-hist2243",
    universityId: "uni-newcastle",
    code: "HIST2243",
    title: "The Practice of History",
    discipline: "history",
    year: 2,
  },
  {
    id: "mod-newcastle-busi2244",
    universityId: "uni-newcastle",
    code: "BUSI2244",
    title: "Organisational Behaviour",
    discipline: "business",
    year: 2,
  },
  {
    id: "mod-newcastle-nurs2245",
    universityId: "uni-newcastle",
    code: "NURS2245",
    title: "Evidence-Based Practice",
    discipline: "nursing",
    year: 2,
  },
  {
    id: "mod-newcastle-comp2246",
    universityId: "uni-newcastle",
    code: "COMP2246",
    title: "Computer Systems and Architecture",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-newcastle-econ2247",
    universityId: "uni-newcastle",
    code: "ECON2247",
    title: "Development Economics",
    discipline: "economics",
    year: 2,
  },
  {
    id: "mod-newcastle-math2248",
    universityId: "uni-newcastle",
    code: "MATH2248",
    title: "Probability and Statistics",
    discipline: "maths",
    year: 2,
  },
  {
    id: "mod-newcastle-med2249",
    universityId: "uni-newcastle",
    code: "MED2249",
    title: "Musculoskeletal and Neurological Systems",
    discipline: "medicine",
    year: 2,
  },

  // University of Nottingham
  {
    id: "mod-nottingham-psyc2251",
    universityId: "uni-nottingham",
    code: "PSYC2251",
    title: "Individual Differences",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-nottingham-law2252",
    universityId: "uni-nottingham",
    code: "LAW2252",
    title: "Land Law",
    discipline: "law",
    year: 2,
  },
  {
    id: "mod-nottingham-hist2253",
    universityId: "uni-nottingham",
    code: "HIST2253",
    title: "Historical Skills and Sources",
    discipline: "history",
    year: 2,
  },
  {
    id: "mod-nottingham-busi2254",
    universityId: "uni-nottingham",
    code: "BUSI2254",
    title: "Financial Management",
    discipline: "business",
    year: 2,
  },
  {
    id: "mod-nottingham-nurs2255",
    universityId: "uni-nottingham",
    code: "NURS2255",
    title: "Pathophysiology and Pharmacology",
    discipline: "nursing",
    year: 2,
  },
  {
    id: "mod-nottingham-comp2256",
    universityId: "uni-nottingham",
    code: "COMP2256",
    title: "Artificial Intelligence",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-nottingham-econ2257",
    universityId: "uni-nottingham",
    code: "ECON2257",
    title: "Economics of Public Policy",
    discipline: "economics",
    year: 2,
  },
  {
    id: "mod-nottingham-math2258",
    universityId: "uni-nottingham",
    code: "MATH2258",
    title: "Numerical Analysis",
    discipline: "maths",
    year: 2,
  },
  {
    id: "mod-nottingham-med2259",
    universityId: "uni-nottingham",
    code: "MED2259",
    title: "Clinical and Communication Skills II",
    discipline: "medicine",
    year: 2,
  },

  // University of Oxford (no undergraduate Business or Nursing degree)
  {
    id: "mod-oxford-psyc2261",
    universityId: "uni-oxford",
    code: "PSYC2261",
    title: "Psychopathology",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-oxford-law2262",
    universityId: "uni-oxford",
    code: "LAW2262",
    title: "Land Law",
    discipline: "law",
    year: 2,
  },
  {
    id: "mod-oxford-hist2263",
    universityId: "uni-oxford",
    code: "HIST2263",
    title: "Historiography and Historical Theory",
    discipline: "history",
    year: 2,
  },
  {
    id: "mod-oxford-comp2266",
    universityId: "uni-oxford",
    code: "COMP2266",
    title: "Software Engineering",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-oxford-econ2267",
    universityId: "uni-oxford",
    code: "ECON2267",
    title: "Econometrics I",
    discipline: "economics",
    year: 2,
  },
  {
    id: "mod-oxford-math2268",
    universityId: "uni-oxford",
    code: "MATH2268",
    title: "Analysis II",
    discipline: "maths",
    year: 2,
  },
  {
    id: "mod-oxford-med2269",
    universityId: "uni-oxford",
    code: "MED2269",
    title: "Cardiovascular and Respiratory Systems",
    discipline: "medicine",
    year: 2,
  },

  // Queen Mary University of London
  {
    id: "mod-queen-mary-psyc2271",
    universityId: "uni-queen-mary",
    code: "PSYC2271",
    title: "Cognitive Psychology",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-queen-mary-law2272",
    universityId: "uni-queen-mary",
    code: "LAW2272",
    title: "Criminal Law",
    discipline: "law",
    year: 2,
  },
  {
    id: "mod-queen-mary-hist2273",
    universityId: "uni-queen-mary",
    code: "HIST2273",
    title: "Sources and Methods in Modern History",
    discipline: "history",
    year: 2,
  },
  {
    id: "mod-queen-mary-busi2274",
    universityId: "uni-queen-mary",
    code: "BUSI2274",
    title: "Marketing Analysis and Strategy",
    discipline: "business",
    year: 2,
  },
  {
    id: "mod-queen-mary-nurs2275",
    universityId: "uni-queen-mary",
    code: "NURS2275",
    title: "Evidence-Based Practice",
    discipline: "nursing",
    year: 2,
  },
  {
    id: "mod-queen-mary-comp2276",
    universityId: "uni-queen-mary",
    code: "COMP2276",
    title: "Data Structures and Algorithms",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-queen-mary-econ2277",
    universityId: "uni-queen-mary",
    code: "ECON2277",
    title: "Intermediate Macroeconomics",
    discipline: "economics",
    year: 2,
  },
  {
    id: "mod-queen-mary-math2278",
    universityId: "uni-queen-mary",
    code: "MATH2278",
    title: "Linear Algebra II",
    discipline: "maths",
    year: 2,
  },
  {
    id: "mod-queen-mary-med2279",
    universityId: "uni-queen-mary",
    code: "MED2279",
    title: "Human Disease and Therapeutics",
    discipline: "medicine",
    year: 2,
  },

  // Queen's University Belfast
  {
    id: "mod-queens-belfast-psyc2281",
    universityId: "uni-queens-belfast",
    code: "PSYC2281",
    title: "Biological Psychology",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-queens-belfast-law2282",
    universityId: "uni-queens-belfast",
    code: "LAW2282",
    title: "Equity and Trusts",
    discipline: "law",
    year: 2,
  },
  {
    id: "mod-queens-belfast-hist2283",
    universityId: "uni-queens-belfast",
    code: "HIST2283",
    title: "Making History: Theory and Practice",
    discipline: "history",
    year: 2,
  },
  {
    id: "mod-queens-belfast-busi2284",
    universityId: "uni-queens-belfast",
    code: "BUSI2284",
    title: "Consumer Behaviour",
    discipline: "business",
    year: 2,
  },
  {
    id: "mod-queens-belfast-nurs2285",
    universityId: "uni-queens-belfast",
    code: "NURS2285",
    title: "Applied Evidence-Based Nursing",
    discipline: "nursing",
    year: 2,
  },
  {
    id: "mod-queens-belfast-comp2286",
    universityId: "uni-queens-belfast",
    code: "COMP2286",
    title: "Databases",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-queens-belfast-econ2287",
    universityId: "uni-queens-belfast",
    code: "ECON2287",
    title: "Money and Banking",
    discipline: "economics",
    year: 2,
  },
  {
    id: "mod-queens-belfast-math2288",
    universityId: "uni-queens-belfast",
    code: "MATH2288",
    title: "Differential Equations",
    discipline: "maths",
    year: 2,
  },
  {
    id: "mod-queens-belfast-med2289",
    universityId: "uni-queens-belfast",
    code: "MED2289",
    title: "Pathology and Pharmacology",
    discipline: "medicine",
    year: 2,
  },

  // University of Sheffield
  {
    id: "mod-sheffield-psyc2291",
    universityId: "uni-sheffield",
    code: "PSYC2291",
    title: "Social Psychology",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-sheffield-law2292",
    universityId: "uni-sheffield",
    code: "LAW2292",
    title: "Public Law",
    discipline: "law",
    year: 2,
  },
  {
    id: "mod-sheffield-hist2293",
    universityId: "uni-sheffield",
    code: "HIST2293",
    title: "The Practice of History",
    discipline: "history",
    year: 2,
  },
  {
    id: "mod-sheffield-busi2294",
    universityId: "uni-sheffield",
    code: "BUSI2294",
    title: "Strategic Management",
    discipline: "business",
    year: 2,
  },
  {
    id: "mod-sheffield-nurs2295",
    universityId: "uni-sheffield",
    code: "NURS2295",
    title: "Clinical Decision Making",
    discipline: "nursing",
    year: 2,
  },
  {
    id: "mod-sheffield-comp2296",
    universityId: "uni-sheffield",
    code: "COMP2296",
    title: "Computer Systems and Architecture",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-sheffield-econ2297",
    universityId: "uni-sheffield",
    code: "ECON2297",
    title: "Intermediate Microeconomics",
    discipline: "economics",
    year: 2,
  },
  {
    id: "mod-sheffield-math2298",
    universityId: "uni-sheffield",
    code: "MATH2298",
    title: "Abstract Algebra",
    discipline: "maths",
    year: 2,
  },
  {
    id: "mod-sheffield-med2299",
    universityId: "uni-sheffield",
    code: "MED2299",
    title: "Cardiovascular and Respiratory Systems",
    discipline: "medicine",
    year: 2,
  },

  // University of Southampton
  {
    id: "mod-southampton-psyc2301",
    universityId: "uni-southampton",
    code: "PSYC2301",
    title: "Developmental Psychology",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-southampton-law2302",
    universityId: "uni-southampton",
    code: "LAW2302",
    title: "Constitutional and Administrative Law",
    discipline: "law",
    year: 2,
  },
  {
    id: "mod-southampton-hist2303",
    universityId: "uni-southampton",
    code: "HIST2303",
    title: "Historical Skills and Sources",
    discipline: "history",
    year: 2,
  },
  {
    id: "mod-southampton-busi2304",
    universityId: "uni-southampton",
    code: "BUSI2304",
    title: "Operations Management",
    discipline: "business",
    year: 2,
  },
  {
    id: "mod-southampton-nurs2305",
    universityId: "uni-southampton",
    code: "NURS2305",
    title: "Evidence-Based Practice",
    discipline: "nursing",
    year: 2,
  },
  {
    id: "mod-southampton-comp2306",
    universityId: "uni-southampton",
    code: "COMP2306",
    title: "Artificial Intelligence",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-southampton-econ2307",
    universityId: "uni-southampton",
    code: "ECON2307",
    title: "Development Economics",
    discipline: "economics",
    year: 2,
  },
  {
    id: "mod-southampton-math2308",
    universityId: "uni-southampton",
    code: "MATH2308",
    title: "Probability and Statistics",
    discipline: "maths",
    year: 2,
  },
  {
    id: "mod-southampton-med2309",
    universityId: "uni-southampton",
    code: "MED2309",
    title: "Musculoskeletal and Neurological Systems",
    discipline: "medicine",
    year: 2,
  },

  // University College London
  {
    id: "mod-ucl-psyc2311",
    universityId: "uni-ucl",
    code: "PSYC2311",
    title: "Cognitive Psychology",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-ucl-law2312",
    universityId: "uni-ucl",
    code: "LAW2312",
    title: "Tort Law",
    discipline: "law",
    year: 2,
  },
  {
    id: "mod-ucl-hist2313",
    universityId: "uni-ucl",
    code: "HIST2313",
    title: "Historiography and Historical Theory",
    discipline: "history",
    year: 2,
  },
  {
    id: "mod-ucl-busi2314",
    universityId: "uni-ucl",
    code: "BUSI2314",
    title: "Marketing Analysis and Strategy",
    discipline: "business",
    year: 2,
  },
  {
    id: "mod-ucl-nurs2315",
    universityId: "uni-ucl",
    code: "NURS2315",
    title: "Pathophysiology and Pharmacology",
    discipline: "nursing",
    year: 2,
  },
  {
    id: "mod-ucl-comp2316",
    universityId: "uni-ucl",
    code: "COMP2316",
    title: "Software Engineering",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-ucl-econ2317",
    universityId: "uni-ucl",
    code: "ECON2317",
    title: "Econometrics I",
    discipline: "economics",
    year: 2,
  },
  {
    id: "mod-ucl-math2318",
    universityId: "uni-ucl",
    code: "MATH2318",
    title: "Real Analysis",
    discipline: "maths",
    year: 2,
  },
  {
    id: "mod-ucl-med2319",
    universityId: "uni-ucl",
    code: "MED2319",
    title: "Human Disease and Therapeutics",
    discipline: "medicine",
    year: 2,
  },

  // University of Warwick (no undergraduate Nursing or Medicine degree)
  {
    id: "mod-warwick-psyc2321",
    universityId: "uni-warwick",
    code: "PSYC2321",
    title: "Individual Differences",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-warwick-law2322",
    universityId: "uni-warwick",
    code: "LAW2322",
    title: "Contract Law",
    discipline: "law",
    year: 2,
  },
  {
    id: "mod-warwick-hist2323",
    universityId: "uni-warwick",
    code: "HIST2323",
    title: "Approaches to History",
    discipline: "history",
    year: 2,
  },
  {
    id: "mod-warwick-busi2324",
    universityId: "uni-warwick",
    code: "BUSI2324",
    title: "Organisational Behaviour",
    discipline: "business",
    year: 2,
  },
  {
    id: "mod-warwick-comp2326",
    universityId: "uni-warwick",
    code: "COMP2326",
    title: "Data Structures and Algorithms",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-warwick-econ2327",
    universityId: "uni-warwick",
    code: "ECON2327",
    title: "Econometrics I",
    discipline: "economics",
    year: 2,
  },
  {
    id: "mod-warwick-math2328",
    universityId: "uni-warwick",
    code: "MATH2328",
    title: "Linear Algebra II",
    discipline: "maths",
    year: 2,
  },

  // University of York
  {
    id: "mod-york-psyc2331",
    universityId: "uni-york",
    code: "PSYC2331",
    title: "Psychopathology",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-york-law2332",
    universityId: "uni-york",
    code: "LAW2332",
    title: "Land Law",
    discipline: "law",
    year: 2,
  },
  {
    id: "mod-york-hist2333",
    universityId: "uni-york",
    code: "HIST2333",
    title: "Sources and Methods in Modern History",
    discipline: "history",
    year: 2,
  },
  {
    id: "mod-york-busi2334",
    universityId: "uni-york",
    code: "BUSI2334",
    title: "Consumer Behaviour",
    discipline: "business",
    year: 2,
  },
  {
    id: "mod-york-nurs2335",
    universityId: "uni-york",
    code: "NURS2335",
    title: "Evidence-Based Practice",
    discipline: "nursing",
    year: 2,
  },
  {
    id: "mod-york-comp2336",
    universityId: "uni-york",
    code: "COMP2336",
    title: "Databases",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-york-econ2337",
    universityId: "uni-york",
    code: "ECON2337",
    title: "Intermediate Macroeconomics",
    discipline: "economics",
    year: 2,
  },
  {
    id: "mod-york-math2338",
    universityId: "uni-york",
    code: "MATH2338",
    title: "Differential Equations",
    discipline: "maths",
    year: 2,
  },
  {
    id: "mod-york-med2339",
    universityId: "uni-york",
    code: "MED2339",
    title: "Cardiovascular and Respiratory Systems",
    discipline: "medicine",
    year: 2,
  },

  // University of Bath (no Law, History, Nursing, or Medicine degree)
  {
    id: "mod-bath-psyc2341",
    universityId: "uni-bath",
    code: "PSYC2341",
    title: "Social Psychology",
    discipline: "psychology",
    year: 2,
  },
  {
    id: "mod-bath-busi2344",
    universityId: "uni-bath",
    code: "BUSI2344",
    title: "Strategic Management",
    discipline: "business",
    year: 2,
  },
  {
    id: "mod-bath-comp2346",
    universityId: "uni-bath",
    code: "COMP2346",
    title: "Artificial Intelligence",
    discipline: "computer-science",
    year: 2,
  },
  {
    id: "mod-bath-econ2347",
    universityId: "uni-bath",
    code: "ECON2347",
    title: "Intermediate Microeconomics",
    discipline: "economics",
    year: 2,
  },
  {
    id: "mod-bath-math2348",
    universityId: "uni-bath",
    code: "MATH2348",
    title: "Probability and Statistics",
    discipline: "maths",
    year: 2,
  },
];


const moduleByIdMap = new Map(modules.map((m) => [m.id, m]));

export function getModuleById(id: string): Module | undefined {
  return moduleByIdMap.get(id);
}

export function getModulesForUniversity(universityId: string): Module[] {
  return modules.filter((m) => m.universityId === universityId);
}

export function getCoursesForUniversity(universityId: string): Discipline[] {
  const set = new Set(getModulesForUniversity(universityId).map((m) => m.discipline));
  return [...set];
}
