import type {
  Advance,
  Competency,
  Discipline,
  MicroBuild,
  Module,
  University,
} from "../types";

export const universities: University[] = [
  {
    id: "uni-manchester",
    slug: "manchester",
    name: "University of Manchester",
    city: "Manchester",
    emailDomains: ["manchester.ac.uk"],
  },
  {
    id: "uni-leeds",
    slug: "leeds",
    name: "University of Leeds",
    city: "Leeds",
    emailDomains: ["leeds.ac.uk"],
  },
  {
    id: "uni-birmingham",
    slug: "birmingham",
    name: "University of Birmingham",
    city: "Birmingham",
    emailDomains: ["student.bham.ac.uk", "bham.ac.uk"],
  },
  {
    id: "uni-bristol",
    slug: "bristol",
    name: "University of Bristol",
    city: "Bristol",
    emailDomains: ["bristol.ac.uk"],
  },
  {
    id: "uni-cambridge",
    slug: "cambridge",
    name: "University of Cambridge",
    city: "Cambridge",
    emailDomains: ["cam.ac.uk"],
  },
  {
    id: "uni-cardiff",
    slug: "cardiff",
    name: "Cardiff University",
    city: "Cardiff",
    emailDomains: ["cardiff.ac.uk"],
  },
  {
    id: "uni-durham",
    slug: "durham",
    name: "Durham University",
    city: "Durham",
    emailDomains: ["durham.ac.uk"],
  },
  {
    id: "uni-edinburgh",
    slug: "edinburgh",
    name: "University of Edinburgh",
    city: "Edinburgh",
    emailDomains: ["ed.ac.uk"],
  },
  {
    id: "uni-exeter",
    slug: "exeter",
    name: "University of Exeter",
    city: "Exeter",
    emailDomains: ["exeter.ac.uk"],
  },
  {
    id: "uni-glasgow",
    slug: "glasgow",
    name: "University of Glasgow",
    city: "Glasgow",
    emailDomains: ["student.gla.ac.uk", "gla.ac.uk"],
  },
  {
    id: "uni-imperial",
    slug: "imperial",
    name: "Imperial College London",
    city: "London",
    emailDomains: ["imperial.ac.uk", "ic.ac.uk"],
  },
  {
    id: "uni-kcl",
    slug: "kcl",
    name: "King's College London",
    city: "London",
    emailDomains: ["kcl.ac.uk"],
  },
  {
    id: "uni-liverpool",
    slug: "liverpool",
    name: "University of Liverpool",
    city: "Liverpool",
    emailDomains: ["liverpool.ac.uk"],
  },
  {
    id: "uni-lse",
    slug: "lse",
    name: "London School of Economics and Political Science",
    city: "London",
    emailDomains: ["lse.ac.uk"],
  },
  {
    id: "uni-newcastle",
    slug: "newcastle",
    name: "Newcastle University",
    city: "Newcastle upon Tyne",
    emailDomains: ["newcastle.ac.uk", "ncl.ac.uk"],
  },
  {
    id: "uni-nottingham",
    slug: "nottingham",
    name: "University of Nottingham",
    city: "Nottingham",
    emailDomains: ["nottingham.ac.uk"],
  },
  {
    id: "uni-oxford",
    slug: "oxford",
    name: "University of Oxford",
    city: "Oxford",
    emailDomains: ["ox.ac.uk"],
  },
  {
    id: "uni-queen-mary",
    slug: "queen-mary",
    name: "Queen Mary University of London",
    city: "London",
    emailDomains: ["qmul.ac.uk"],
  },
  {
    id: "uni-queens-belfast",
    slug: "queens-belfast",
    name: "Queen's University Belfast",
    city: "Belfast",
    emailDomains: ["qub.ac.uk"],
  },
  {
    id: "uni-sheffield",
    slug: "sheffield",
    name: "University of Sheffield",
    city: "Sheffield",
    emailDomains: ["sheffield.ac.uk", "shef.ac.uk"],
  },
  {
    id: "uni-southampton",
    slug: "southampton",
    name: "University of Southampton",
    city: "Southampton",
    emailDomains: ["soton.ac.uk"],
  },
  {
    id: "uni-ucl",
    slug: "ucl",
    name: "University College London",
    city: "London",
    emailDomains: ["ucl.ac.uk"],
  },
  {
    id: "uni-warwick",
    slug: "warwick",
    name: "University of Warwick",
    city: "Coventry",
    emailDomains: ["warwick.ac.uk"],
  },
  {
    id: "uni-york",
    slug: "york",
    name: "University of York",
    city: "York",
    emailDomains: ["york.ac.uk"],
  },
  {
    id: "uni-bath",
    slug: "bath",
    name: "University of Bath",
    city: "Bath",
    emailDomains: ["bath.ac.uk"],
  },
];

